### ISSUE TITLE
Db2val check fails

### ISSUE THREAD

**Issue by Flor-IT** [bernardoVale/ansible-role-db2#26]
Hello again,
this time I noticed that the step "Validating the current installation" is not working. I don´t know why, but the command db2val is not producing any output. The validate step searches for the output 'DBI1335I' - which fails. The DB2 installation seems to be clean.

Of course one can skip the validation with the 'validate'-Tag. I´m using DB2 V10.5-FP7

Thanks,
Oliver

**Comment by Flor-IT** [comment]
When I run the db2val command as an instance user it´s producing the right output. Only as root, which I use for the role execution there is no output

**Comment by bernardoVale** [comment]
Hello, Oliver. This is weird. Did you check de result code of db2val?

Could you provide the output?

Maybe IBM changed this behavior a little bit. If the resultcode is 0 we could make a little change on the `db2val` task:

**from**:
`failed_when: "'DBI1335I' not in db2_val.stdout"`
**to**:
`failed_when: "'DBI1335I' not in db2_val.stdout or db2_val.rc != 0"`

**Comment by Flor-IT** [comment]
Yes a 
`echo "$?"`
returns 0. 

But I don´t know if the db2val returns something != 0 in the case of failure. If so you could use "and" for additional return value check. The mentioned "or" would not help.

I have to find a way to execute the the command as the instance User.

**Comment by bernardoVale** [comment]
Could you provide a link to download this binary? I'd like to test with it.

**Comment by Flor-IT** [comment]
I have sent you an email.

**Comment by bernardoVale** [comment]
Hello @Flor-IT, I've just tried with your db2 binary and a CentOS 7 box.

Unfortunately, I wasn't able to reproduce the error, the role executed fine.

Take a look at the validation output:

With root on ansible:

```
TASK [bernardoVale.db2 : Validate results] *************************************
ok: [10.200.0.202] => {
    "db2_val": {
        "changed": false,
        "cmd": [
            "/opt/ibm/db2/V10.5/bin/db2val",
            "-o"
        ],
        "delta": "0:00:22.571167",
        "end": "2016-07-14 10:01:02.485887",
        "failed": false,
        "failed_when_result": false,
        "rc": 0,
        "start": "2016-07-14 10:00:39.914720",
        "stderr": "",
        "stdout": "DBI1379I  The db2val command is running. This can take several minutes.\n\nDBI1335I  Installation file validation for the DB2 copy installed at\n      /opt/ibm/db2/V10.5 was successful.\n\nDBI1343I  The db2val command completed successfully. For details, see\n      the log file /tmp/db2val-160714_100039.log.",
        "stdout_lines": [
            "DBI1379I  The db2val command is running. This can take several minutes.",
            "",
            "DBI1335I  Installation file validation for the DB2 copy installed at",
            "      /opt/ibm/db2/V10.5 was successful.",
            "",
            "DBI1343I  The db2val command completed successfully. For details, see",
            "      the log file /tmp/db2val-160714_100039.log."
        ],
        "warnings": []
    }
}
```

With root:

```
[root@lb2-viewrds tmp]# /opt/ibm/db2/V10.5/bin/db2val -o
DBI1379I  The db2val command is running. This can take several minutes.

DBI1335I  Installation file validation for the DB2 copy installed at
      /opt/ibm/db2/V10.5 was successful.

DBI1343I  The db2val command completed successfully. For details, see
      the log file /tmp/db2val-160714_095809.log.
```

I noticed some problems while trying to extract this .tar.gz. The unarchive module wasn't able to decompress it so I turned the file a tar with `gunzip db2_server_V10.5-FP7.tar.gz` and then run the role.

```
# tar -zxvf db2_server_V10.5-FP7.tar.gz
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Comment by bernardoVale** [comment]
Hello @Flor-IT , did you had a chance to test with another tar file?

**Comment by whynotnowtoday** [comment]
Sorry not yet ... my work around was successful .. but I will make an effort to retest the change you made in the next few days 

Sent from my Samsung device

-------- Original message --------

**Comment by Flor-IT** [comment]
@whynotnowtoday wrong issue? ;) 

@bernardoVale I asked somebody in my company about that thing and he said, that db2val as root can behave strange. At the Moment I can live with the workaround to skip validation. Thank You!

**Comment by bernardoVale** [comment]
Got it @Flor-IT, thank you.
