### ISSUE TITLE
db2 module fails on  systems such as Ubuntu  that use dash  of /bin/sh 

### ISSUE THREAD

**Issue by whynotnowtoday** [bernardoVale/ansible-role-db2#27]
db2 module cant find the 'source' command on systems where dash is default.  . Setting environment  config setting executable does  not help  - see also    https://github.com/ansible/ansible/issues/1238

**Comment by bernardoVale** [comment]
Hello @whynotnowtoday . Thanks for your feedback. I'll try to change that part of the code.

**Comment by whynotnowtoday** [comment]
Hi 
Found a work  around ...
If you update the run_command calls in the module by adding executable='/bin/bash'parm  it seems to work 

Barry 
Sent from my Samsung device

-------- Original message --------

**Comment by bernardoVale** [comment]
Hello Barry, yes that could also work.

I've just updated the code to make it work. Basically, I've changed from `source` to `.`. Could you try with the latest code?

Ignore the build failure, It was my mistake.

**Comment by bernardoVale** [comment]
Hello @whynotnowtoday , did you had a chance to test with the latest commit?
