### ISSUE TITLE
with_items since ansible v2.2

### ISSUE THREAD

**Issue by movcale** [bernardoVale/ansible-role-db2#28]
Hello,

according to
https://github.com/ansible/ansible/issues/23496#issuecomment-293332601

with_items requires explicit jinja2 wrapping:
with_items: "{{ databases }}"

please fix it in tasks

**Comment by bernardoVale** [comment]
Thanks for the heads up @movcale, I will fix ASAP.

**Comment by randomswdev** [comment]
I have a fix ready for this issue. May I push a branch and create a pull request?

**Comment by bernardoVale** [comment]
awesome @randomswdev , please create a PR!

**Comment by bernardoVale** [comment]
Fixed in PR #29
